# Generated by Django 3.2 on 2022-12-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20221213_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industry_type',
            new_name='industryname',
        ),
    ]
