# Generated by Django 3.2 on 2022-12-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_rename_industry_type_company_industryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industryname',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='industrytype',
            old_name='industryname',
            new_name='name',
        ),
    ]
